CALL wraptool sign --verbose --account jimmyhung --wcguid E0DF4D80-3BBC-11E6-840B-005056875CC3 --keyfile March1Sign.p12 --keypassword 1234 --in VisualStudio2012\PT_Release\MSg.aaxplugin\Contents\x64\MSg.aaxplugin --out VisualStudio2012\PT_Release\MSg.aaxplugin\Contents\x64\MSg.aaxplugin

CALL wraptool sign --verbose --account jimmyhung --wcguid E0DF4D80-3BBC-11E6-840B-005056875CC3 --keyfile March1Sign.p12 --keypassword 1234 --in VisualStudio2012\PT_Debug\MSg.aaxplugin\Contents\x64\Msg.aaxplugin --out VisualStudio2012\PT_Debug\MSg.aaxplugin\Contents\x64\MSg.aaxplugin

